const rhymeData = [
    // --- Vần 2 chữ cái (danh sách cũ) ---
    { rhyme: 'ai', word: 'cái tai' },
    { rhyme: 'ao', word: 'ngôi sao' },
    { rhyme: 'au', word: 'quả cau' },
    { rhyme: 'âu', word: 'con trâu' },
    { rhyme: 'ay', word: 'máy bay' },
    { rhyme: 'ây', word: 'cái cây' },
    { rhyme: 'eo', word: 'con mèo' },
    { rhyme: 'êu', word: 'cái lều' },
    { rhyme: 'ia', word: 'cái thìa' },
    { rhyme: 'iu', word: 'cái rìu' },
    { rhyme: 'oa', word: 'bông hoa' },
    { rhyme: 'oe', word: 'chim chích chòe' },
    { rhyme: 'oi', word: 'con voi' },
    { rhyme: 'ôi', word: 'cái chổi' },
    { rhyme: 'ơi', word: 'đồ chơi' },
    { rhyme: 'ua', word: 'con rùa' },
    { rhyme: 'uê', word: 'hoa huệ' },
    { rhyme: 'ui', word: 'cái túi' },
    { rhyme: 'uy', word: 'khuy áo' },
    { rhyme: 'ưa', word: 'quả dưa' },
    { rhyme: 'ưi', word: 'gửi thư' },
    { rhyme: 'ưu', word: 'con cừu' },

    { rhyme: 'am', word: 'quả cam' },
    { rhyme: 'ap', word: 'xe đạp' },
    { rhyme: 'ăm', word: 'tăm tre' },
    { rhyme: 'ăp', word: 'bắp ngô' },
    { rhyme: 'âm', word: 'cây nấm' },
    { rhyme: 'âp', word: 'mập mạp' },
    { rhyme: 'em', word: 'kem mút' },
    { rhyme: 'ep', word: 'đôi dép' },
    { rhyme: 'êm', word: 'ban đêm' },
    { rhyme: 'êp', word: 'nhà bếp' },
    { rhyme: 'im', word: 'con chim' },
    { rhyme: 'ip', word: 'bắt nhịp' },
    { rhyme: 'om', word: 'đom đóm' },
    { rhyme: 'op', word: 'con cọp' },
    { rhyme: 'ôm', word: 'con tôm' },
    { rhyme: 'ôp', word: 'hộp sữa' },
    { rhyme: 'ơm', word: 'bát cơm' },
    { rhyme: 'ơp', word: 'tia chớp' },
    { rhyme: 'um', word: 'chùm nho' },
    { rhyme: 'up', word: 'búp bê' },

    { rhyme: 'an', word: 'bàn tay' },
    { rhyme: 'at', word: 'bãi cát' },
    { rhyme: 'ăn', word: 'khăn mặt' },
    { rhyme: 'ăt', word: 'đôi mắt' },
    { rhyme: 'ân', word: 'bàn chân' },
    { rhyme: 'ât', word: 'lật đật' },
    { rhyme: 'en', word: 'cái kèn' },
    { rhyme: 'et', word: 'đất sét' },
    { rhyme: 'ên', word: 'mũi tên' },
    { rhyme: 'êt', word: 'con rết' },
    { rhyme: 'in', word: 'đèn pin' },
    { rhyme: 'it', word: 'con vịt' },
    { rhyme: 'on', word: 'ngón tay' },
    { rhyme: 'ot', word: 'chim hót' },
    { rhyme: 'ôn', word: 'con chồn' },
    { rhyme: 'ôt', word: 'cột cờ' },
    { rhyme: 'ơn', word: 'sơn ca' },
    { rhyme: 'ơt', word: 'cái vợt' },
    { rhyme: 'un', word: 'con giun' },
    { rhyme: 'ut', word: 'bút chì' },
    { rhyme: 'ưn', word: '' },
    { rhyme: 'ưt', word: 'mứt tết' },

    { rhyme: 'ac', word: 'hạt lạc' },
    { rhyme: 'ăc', word: 'màu sắc' },
    { rhyme: 'âc', word: 'quả gấc' },
    { rhyme: 'ec', word: 'kêu éc éc' },
    { rhyme: 'êc', word: '' },
    { rhyme: 'ic', word: 'zíc zắc' },
    { rhyme: 'oc', word: 'con cóc' },
    { rhyme: 'ôc', word: 'con ốc' },
    { rhyme: 'uc', word: 'hoa cúc' },
    { rhyme: 'ưc', word: 'lọ mực' },

    // --- Vần 3 chữ cái mới ---
    { rhyme: 'oai', word: 'quả xoài' },
    { rhyme: 'oao', word: 'ngoao ngoao' },
    { rhyme: 'oay', word: 'vòng xoáy' },
    { rhyme: 'uay', word: '' },
    { rhyme: 'uôi', word: 'nải chuối' },
    { rhyme: 'uya', word: 'đêm khuya' },
    { rhyme: 'uyu', word: 'khuỷu tay' },
    { rhyme: 'iêu', word: 'con diều' },
    { rhyme: 'yêu', word: 'đáng yêu' },
    { rhyme: 'ươi', word: 'quả bưởi' },
    { rhyme: 'oam', word: 'nhai nhồm ngoàm' },
    { rhyme: 'oap', word: '' },
    { rhyme: 'oăm', word: 'mũi khoằm' },
    { rhyme: 'oăp', word: '' },
    { rhyme: 'iêm', word: 'cái kim tiêm' },
    { rhyme: 'iêp', word: 'tấm thiếp' },
    { rhyme: 'yêm', word: 'cái yếm' },
    { rhyme: 'yêp', word: '' },
    { rhyme: 'uôm', word: 'cánh buồm' },
    { rhyme: 'uôp', word: '' },
    { rhyme: 'ươm', word: 'con bướm' },
    { rhyme: 'ươp', word: 'mướp hương' },
    { rhyme: 'oan', word: 'hoa xoan' },
    { rhyme: 'oat', word: 'hoạt hình' },
    { rhyme: 'oăn', word: 'tóc xoăn' },
    { rhyme: 'oăt', word: 'nhọn hoắt' },
    { rhyme: 'uân', word: 'mùa xuân' },
    { rhyme: 'uât', word: 'nghệ thuật' },
    { rhyme: 'iên', word: 'viên bi' },
    { rhyme: 'iêt', word: 'thời tiết' },
    { rhyme: 'yên', word: 'chim yến' },
    { rhyme: 'yêt', word: 'niêm yết' },
    { rhyme: 'uôn', word: 'chuồn chuồn' },
    { rhyme: 'uôt', word: 'con chuột' },
    { rhyme: 'ươn', word: 'con lươn' },
    { rhyme: 'ươt', word: 'trượt ngã' },
    { rhyme: 'oac', word: 'áo khoác' },
    { rhyme: 'oăc', word: 'dấu ngoặc' },
    { rhyme: 'iêc', word: 'rạp xiếc' },
    { rhyme: 'uôc', word: 'ngọn đuốc' },
    { rhyme: 'ươc', word: 'cái lược' },
    { rhyme: 'ang', word: 'cái bảng' },
    { rhyme: 'ăng', word: 'măng tre' },
    { rhyme: 'âng', word: 'vầng trăng' },
    { rhyme: 'eng', word: 'cái xẻng' },
    { rhyme: 'ong', word: 'con ong' },
    { rhyme: 'ông', word: 'bông hoa' },
    { rhyme: 'ung', word: 'quả sung' },
    { rhyme: 'ưng', word: 'quả trứng' },
    { rhyme: 'anh', word: 'bức tranh' },
    { rhyme: 'ach', word: 'cuốn sách' },
    { rhyme: 'ênh', word: 'bấp bênh' },
    { rhyme: 'êch', word: 'con ếch' },
    { rhyme: 'inh', word: 'máy vi tính' },
    { rhyme: 'ich', word: 'tờ lịch' },

    // --- Vần 4 chữ cái mới ---
    { rhyme: 'oang', word: 'áo choàng' },
    { rhyme: 'oăng', word: 'lăng quăng' },
    { rhyme: 'iêng', word: 'cái kiềng' },
    { rhyme: 'yêng', word: 'chim yểng' },
    { rhyme: 'uông', word: 'quả chuông' },
    { rhyme: 'ương', word: 'cái gương' },
    { rhyme: 'oanh', word: 'doanh trại' },
    { rhyme: 'oach', word: 'thu hoạch' },
    { rhyme: 'uynh', word: 'phụ huynh' },
    { rhyme: 'uych', word: 'ngã huỵch' },
    { rhyme: 'uyên', word: 'chim quyên' },
    { rhyme: 'uyêt', word: 'băng tuyết' }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = rhymeData;
}
